### ISSUE TITLE
VSCode extension 

### ISSUE THREAD

**Issue by amotupal** [MicrosoftLearning/angular2-typescript#2]
What's the VSCode extension you used in the demo? When I checked there are bunch of extensions in VSCode for angular.

**Comment by GeekTrainer** [comment]
There are a couple of snippet packets, in particular Angular2 TypeScript with HTML directives Snippets, that Speros used. Otherwise, he was using some custom snippets.
<img width="412" alt="angular" src="https://cloud.githubusercontent.com/assets/6109729/17487797/3b117b02-5d4b-11e6-99c8-b1172ad19cc9.png">
